### ISSUE TITLE
Cannot build project: ElixirScript.CompileError find_used_modules

### ISSUE THREAD

**Issue by auxbuss** [elixirscript/todo-elixirscript#1]
First off, I couldn't find `elixir 1.5.0-otp-20` as required in `.tools-version`, so I'm using `elixir 1.5.0`.

After
```
mix deps.get
cd assets && npm install && cd ..
```
I get:
```
❯ mix phx.server
** (ElixirScript.CompileError) An error occurred while compiling Enum: Debug info not available
    lib/elixir_script/passes/find_used_modules.ex:29: ElixirScript.FindUsedModules.do_execute/2
    (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:675: Enum.each/2
    lib/elixir_script/passes/find_used_modules.ex:281: ElixirScript.FindUsedModules.walk/2
    (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:675: Enum.each/2
    (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:675: Enum.each/2
    (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:675: Enum.each/2
    (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:675: Enum.each/2
    (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:675: Enum.each/2
    (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:675: Enum.each/2
    (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:675: Enum.each/2
    (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:675: Enum.each/2
```
In addition, I get:
```
❯ mix clean
** (File.Error) could not remove file "assets/js/build/elixirscript.build.js": no such file or directory
    (elixir) lib/file.ex:900: File.rm!/1
    lib/mix/tasks/compile.elixir_script.ex:53: Mix.Tasks.Compile.ElixirScript.clean/0
    (mix) lib/mix/tasks/clean.ex:30: anonymous fn/2 in Mix.Tasks.Clean.run/1
    (elixir) lib/enum.ex:1811: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix) lib/mix/tasks/clean.ex:27: Mix.Tasks.Clean.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
```

**Comment by tjheeta** [comment]
Same error. Am using erlang 20.1 from erlang-solutions and elixir 1.5.1-1. 

This project using elixirscript 0.27 works perfectly fine:
https://github.com/grappendorf/elixir_todo_app

**Comment by bryanjos** [comment]
Elixir must be compiled using OTP 20. The version in the .tool-versions file, `elixir 1.5.0-otp-20` is a version that is compiled with OTP 20. The .tool-versions file works with asdf. But the OTP 20 specific build is something that is made available by the Elixir team. You can find more information about it here: https://github.com/hexpm/bob#elixir-builds

**Comment by auxbuss** [comment]
Okay, thanks for that. Listing all elixirs in asdf does not show the build versions, and I didn't know about the various OTP build versions. Good to know 👍 

For ref: the asdf-elixir plugin page mentions how to install them:
https://github.com/asdf-vm/asdf-elixir
Thus: `asdf install elixir 1.5.0-otp-20` is required.

The elixir/OTP builds are listed here:
https://github.com/hexpm/bob/blob/master/scripts/elixir_to_otp.exs
